### ISSUE TITLE
Set up .gitignore file

### ISSUE THREAD

**Issue by tomasvn** [Pexeus/LCSS#1]
* add .gitignore file
  * add node_modules
  * add package_lock.json

* node_modules are big in size, put them in gitignore file, let user innstall deps via `npm i` when developing

**Comment by Pexeus** [comment]
Added node_modules! why package_lock.json?

**Comment by tomasvn** [comment]
it can be generated by installing dependencies, if you have package-lock
and package.json outsync it might cause issues so better to leave it from
repo, but some devs leave there some put in ignore, you might check other
sources and decide

po 6. 7. 2020 v 11:21 odesílatel Pexeus <notifications@github.com> napsal:
