### ISSUE TITLE
[Feature] Use some sort of UI kit to style the app

### ISSUE THREAD

**Issue by tomasvn** [Pexeus/LCSS#14]
- [Fomantic UI](https://fomantic-ui.com/)
- [Tachynos](http://tachyons.io/)
- [Tailwind css](https://tailwindcss.com/)

- I might start this one, there is not a lot of html and css, I might refactor the css in the end

**Comment by Pexeus** [comment]
Not quite sure about that one... i kinda enjoy doing it without, but at the same time, a new look for the program would be interesting! You can give it a try but maybe i will prefer the old one...

**Comment by tomasvn** [comment]
I dont have to use them, I can take a look at some of the core elements and use it, instead bringing the whole css library for couple of elements
