### ISSUE TITLE
Fix values for opacity and transition

### ISSUE THREAD

**Issue by tomasvn** [Pexeus/LCSS#6]
- Opacity is a unitless, value is between 0 and 1
- transition-duration can take `ms` or `s` as unit

**Comment by Pexeus** [comment]
i see, i will try to fix it tomorrow.

**Comment by Pexeus** [comment]
Finally done it! i reworked the whole dropdowns part. dropdowns.js now scans every CSS file before the editor gets generated and collects data for the dropdowns. And i also added an "empty unit", as well as ms or s.
