### ISSUE TITLE
setting up constants etc.

### ISSUE THREAD

**Issue by tomasvn** [Pexeus/LCSS#8]
- Go through js files and initialize variables
- eg. when I have declared `const fs = require('fs')` as you had in other files, `console.log` has errors
  - even tough somewhere you have at uninitialized

**Comment by tomasvn** [comment]
- the issue seems to be when declaring `fs` module in `clear.js`
- if you have `fs = require('fs');` - it works
- but if you have `const fs = require('fs');` it throws errors and the app doesnt work

**Comment by Pexeus** [comment]
yes, i have seen that before, i think i its because i have the imports in multiple files. Would it be a good idea to create a "import.js" file, with all the imports?

**Comment by tomasvn** [comment]
yes it would be a good idea, it would probably create cleaner code, because you seem to be settled on es6, but when you try to use those es6 features it breaks your code :D I am not that good with es6 but this seems to a be a good idea to implement [exporting modules](https://www.sitepoint.com/understanding-module-exports-exports-node-js/) and somehow combine it into one file that you will load in `<script src="..."></script>`

**Comment by tomasvn** [comment]
[See #9 ](https://github.com/Pexeus/LCSS/pull/9l)

**Comment by Pexeus** [comment]
Yo dude, first, thanks so much for all the work on the setup, it looks so clean now! To be honest. i dont even now what "ES6" is, (you have to keep in mind, all my JS knowledge is googling stuff xD). but i understand the way u made things work in the setup scripts, and i really see the advantages. I think taking a similar approach on the editor would be great, but right now, im focused on some other things including:

- Better dropdowns: i wanna try to create a script that collocts data form the imported CSS files, and then creates lists for the dropdowns. (as well as fixing the bug with the unitless values)

- making some scripts to easy package the app and create an installer

- creating a download page

I have now created an "experimental" branch, i hope thats what u needed!

**Comment by tomasvn** [comment]
😄 oh, i tought that you know some es6 because you where using let, const, arrow functions etc

**Comment by Pexeus** [comment]
i think i just used the stuff i found online... What do you think about the code in general? what mistakes did i made?

**Comment by tomasvn** [comment]
i see...it was ok, you have to use const and let more, read about them, you just left them without setting proper `const`, eg. `fs = require(fs)` this is bad, it might result in errors, you have to declare variables

**Comment by tomasvn** [comment]
I might rework the editor script part, I will try to debug the code, but there is more code than in the setup part, issue is resolved, I am closing this issue
